{{- if .Values.lago.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-lago-sa-patch
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-patcher-sa
      restartPolicy: Never
      containers:
      - name: patch-serviceaccount
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl patch serviceaccount {{ .Release.Name }}-serviceaccount \
            -n {{ .Values.global.namespace }} \
            -p '{"metadata":{"annotations":{"eks.amazonaws.com/role-arn":"{{ .Values.lago.serviceAccount.roleArn }}"}}}'
          echo "ServiceAccount patched successfully with IRSA role annotation"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-patcher-sa
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-patcher-role
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-patcher-binding
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-patcher-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-patcher-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
