apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.global.namespace | default "web-services" }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          args:
            - "--config"
            - "/app/config.yaml"
          env:
            - name: AWS_REGION
              value: {{ .Values.env.aws_region | quote }}
            - name: LITELLM_MODE
              value: "PRODUCTION"
            - name: LITELLM_SALT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: litellm_salt_key
            - name: USE_PRISMA_MIGRATE
              value: "True"
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: litellm_master_key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: database_url
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: redis_host
            - name: REDIS_PORT
              value: "{{ .Values.env.litellmRedisPort }}"
            - name: LITELLM_REDIS_PORT
              value: "{{ .Values.env.litellmRedisPort }}"
            - name: TOGETHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: together_api_key
            - name: SEALION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: sealion_api_key
            - name: VLLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key
            - name: VLLM_API_KEY_EXOSCALE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key_exoscale
            - name: VLLM_API_KEY_ANU
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key_anu
            - name: VLLM_API_KEY_CSCS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key_cscs
            - name: VLLM_API_KEY_CUDO
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key_cudo
            - name: VLLM_API_KEY_HH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key_hh
            - name: VLLM_API_KEY_INTEL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: vllm_api_key_intel
            - name: CIRRASCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: cirrascale_api_key
            - name: PARASCALE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: parascale_api_key
            - name: MULTIVERSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: multiverse_api_key
            {{- if .Values.lago.enabled }}
            - name: LAGO_API_BASE
              value: "http://web-services-api-svc.web-services.svc.cluster.local:3000"
            - name: LAGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: lago_api_key
            - name: LAGO_API_EVENT_CODE
              value: "{{ .Values.lago.eventCode }}"
            - name: LAGO_API_CHARGE_BY
              value: "{{ .Values.lago.chargeBy }}"
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: custom-auth-volume
              mountPath: /app/custom_auth.py
              subPath: custom_auth.py
              readOnly: true
            - name: custom-lago-callback-volume
              mountPath: /app/custom_lago_callback.py
              subPath: custom_lago_callback.py
              readOnly: true
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app.name }}-config
        - name: custom-auth-volume
          configMap:
            name: {{ .Values.app.name }}-custom-auth
        - name: custom-lago-callback-volume
          configMap:
            name: {{ .Values.app.name }}-custom-lago-callback